// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Segmen-Pixel and Seg-Studio contributors
export type ImageItem = {
  id: string;
  name: string;
  filename: string;
  set: "none" | "train" | "val" | "test";
  width: number;
  height: number;
  annotation?: {
    hasMask: boolean;
    /** True if mask contains non-zero (foreground) pixels.
     *  hasMask=true + hasForeground=false means "annotated as all-background". */
    hasForeground?: boolean;
    /** True only when explicitly marked clean via Mark Clean button. */
    markedClean?: boolean;
    classIds?: number[];
    revision: number;
    lastSavedAt?: string | null;
    /** True when this item was generated by the Perlin CutPaste synthesis
     *  endpoint. Synthesized items participate in training like normal
     *  labeled items but the UI adds a 🧪 badge so the user can review
     *  and delete unnatural ones. */
    synthetic?: boolean;
    /** Host image stem used as the background for this synthesized sample. */
    synthSource?: string;
    /** Stems of the labeled images whose defect crops were pasted in. */
    synthDefectSources?: string[];
  };
};

export type CacheEntry = {
  width: number;
  height: number;
  maskIndex: Uint8Array;
  touched: Uint8Array; // 1 = pixel was edited, 0 = untouched (ignore on save)
  dirty: boolean;
  revision: number;
  undoStack: { indices: Uint32Array; prevValues: Uint8Array }[];
  redoStack: { indices: Uint32Array; prevValues: Uint8Array }[];
  lastSavedAt?: string | null;
};

export const TOOL_LABELS = [
  { id: "brush", label: "Brush", labelJa: "ブラシ", shortcut: "B" },
  { id: "eraser", label: "Eraser", labelJa: "消しゴム", shortcut: "E" },
  { id: "move", label: "Move", labelJa: "移動", shortcut: "V" },
  { id: "bucket", label: "Bucket", labelJa: "塗りつぶし", shortcut: "G" },
  { id: "wand", label: "Wand", labelJa: "自動選択", shortcut: "W" },
  { id: "sam", label: "SAM", labelJa: "SAM", shortcut: "S" },
  { id: "sambox", label: "SAM Box", labelJa: "SAMボックス", shortcut: "X" },
  { id: "measure", label: "Measure", labelJa: "計測", shortcut: "M" },
  { id: "spotdetect", label: "Spot", labelJa: "スポット検出", shortcut: "D" },
  { id: "superpixel", label: "SPix", labelJa: "スーパーピクセル", shortcut: "P" },
  { id: "cracktrace", label: "Crack", labelJa: "クラック検出", shortcut: "C" }
] as const;

export type ToolId = (typeof TOOL_LABELS)[number]["id"];

export const CLASS_COLOR_PALETTE: [number, number, number][] = [
  [255, 0, 0],
  [0, 122, 255],
  [0, 200, 120],
  [255, 165, 0],
  [213, 94, 0],
  [0, 206, 209],
  [255, 20, 147],
  [128, 128, 0],
  [0, 128, 128],
  [220, 20, 60],
];

/** @deprecated Use CLASS_COLOR_PALETTE + nextPaletteColor() instead */
export const DEFAULT_CLASS_COLORS: Record<number, [number, number, number]> = {
  1: [255, 0, 0],
  2: [0, 122, 255],
  3: [0, 200, 120],
};

/** Pick the next unused color from the palette (FIFO order). */
export function nextPaletteColor(usedColors: [number, number, number][]): [number, number, number] {
  const usedSet = new Set(usedColors.map(c => `${c[0]},${c[1]},${c[2]}`));
  for (const c of CLASS_COLOR_PALETTE) {
    if (!usedSet.has(`${c[0]},${c[1]},${c[2]}`)) return c;
  }
  // All palette colors used — generate a deterministic color based on count
  const idx = usedColors.length % CLASS_COLOR_PALETTE.length;
  const base = CLASS_COLOR_PALETTE[idx]!;
  return [
    Math.min(255, base[0] + 40),
    Math.min(255, base[1] + 40),
    Math.min(255, base[2] + 40),
  ];
}
