#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Segmen-Pixel and Seg-Studio contributors
"""Deterministically render seg-studio.ico (the committed launcher icon).

The .ico next to this script is generated by this file — geometric shapes
only (no fonts), so the output is byte-stable across machines with the
same Pillow major version. Re-run after editing and commit both files:

    python scripts/installer_assets/make_icon.py
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw

# Okabe-Ito palette (colorblind-safe; project UI guideline: no purple)
BLUE = (0, 114, 178, 255)        # #0072B2 background
VERMILION = (213, 94, 0, 255)    # #D55E00 accent instance
WHITE = (255, 255, 255, 255)

SIZE = 256
ICO_SIZES = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]


def render() -> Image.Image:
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # Rounded-square app tile
    d.rounded_rectangle([8, 8, SIZE - 8, SIZE - 8], radius=48, fill=BLUE)
    # Abstract segmentation masks: two detected "instances"
    d.ellipse([48, 72, 148, 196], fill=WHITE)                      # blob 1
    d.rounded_rectangle([132, 56, 216, 140], radius=24, fill=VERMILION)  # blob 2
    # Instance outline marks (count rings)
    d.ellipse([48, 72, 148, 196], outline=BLUE, width=8)
    d.rounded_rectangle([132, 56, 216, 140], radius=24, outline=BLUE, width=8)
    return img


def main() -> None:
    out = Path(__file__).resolve().parent / "seg-studio.ico"
    render().save(out, format="ICO", sizes=ICO_SIZES)
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
